export { default as Arduino } from './Arduino.svg'
export { default as AzureDevops } from './Azure Devops.svg'
export { default as Bootstrap } from './Bootstrap.svg'
export { default as CSharp } from './CSharp.svg'
export { default as CSS } from './CSS3.svg'
export { default as Docker } from './Docker.svg'
export { default as Git } from './Git.svg'
export { default as GitHub } from './GitHub.svg'
export { default as HTML } from './HTML5.svg'
export { default as Java } from './Java.svg'
export { default as JavaScript } from './JavaScript.svg'
export { default as MongoDB } from './MongoDB.svg'
export { default as PHP } from './PHP.svg'
export { default as PostgresSQL } from './PostgresSQL.svg'
export { default as Python } from './Python.svg'
export { default as ReactIcon } from './React.svg'
export { default as Sass } from './Sass.svg'
export { default as TypeScript } from './TypeScript.svg'
